### ISSUE TITLE
initial constructor

### ISSUE THREAD

**Issue by coricidin12** [WesSouza/lgtv-ip-control#41]
What am I doing wrong here? I'm getting "LGTV is not a constructor". Here is my code

`var LGTV = require('lgtv-ip-control');
const tv = new LGTV('192.168.X.XX', 'XXXXXXXXXX', 'XXXXXXX');
tv.connect()
.then(async () => {
    console.log('powering on');
    tv.powerOn()
})
.catch(console.error);`

**Comment by WesSouza** [comment]
There is no default export to this module, so `LGTV` on your code is getting an object with all of the exported classes.

I'd suggest using destructuring with `require`:

```js
const { LGTV } = require('lgtv-ip-control');
```
