### ISSUE TITLE
Picture Settings

### ISSUE THREAD

**Issue by helgek** [WesSouza/lgtv-ip-control#59]
Hi,

I finally found solution to change e.g. picture presets. Please see my last comment at:

https://community.home-assistant.io/t/lg-webos-change-picture-setting-mode-with-scripts/262915

Maybe this could be useful for your project as well?

Thanks and regards
Helge

**Comment by helgek** [comment]
Additional discussion: https://github.com/merdok/homebridge-webos-tv/issues/371

**Comment by WesSouza** [comment]
I'm closing this given it's not possible using the IP Control protocol, but it seems that WebSockets are indeed a better way to interface with the TVs than this 😛.
