### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by oznetmaster** [WesSouza/lgtv-ip-control#64]
The "npm install lgtv-ip-control" command fails:

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Development (x86)\\nodejs\\node.exe',
1 verbose cli   'D:\\Users\\njc\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'lgtv-ip-control'
1 verbose cli ]
2 info using npm@4.5.0
3 info using node@v14.17.0
4 verbose config Skipping project config: C:\Users\njc/.npmrc. (matches userconfig)
5 silly loadCurrentTree Starting
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 verbose stack TypeError: cb.apply is not a function
8 verbose stack     at D:\Users\njc\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:287:18
8 verbose stack     at FSReqCallback.oncomplete (fs.js:193:5)
9 verbose cwd C:\Users\njc
10 verbose Windows_NT 10.0.19043
11 verbose argv "C:\\Development (x86)\\nodejs\\node.exe" "D:\\Users\\njc\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "lgtv-ip-control"
12 verbose node v14.17.0
13 verbose npm  v4.5.0
14 error cb.apply is not a function
15 verbose exit [ 1, true ]

**Comment by WesSouza** [comment]
This might be because you are running npm 4.5.0, can you try upgrading npm and trying again?

```sh
npm i -g npm@latest
```

**Comment by oznetmaster** [comment]
Microsoft Windows [Version 10.0.19043.1052]
(c) Microsoft Corporation. All rights reserved.

C:\Users\xxx>npm i -g npm@latest
npm ERR! cb.apply is not a function

**Comment by WesSouza** [comment]
You might want to reinstall node or troubleshoot that on your machine. This problem is not related to the library.
