### ISSUE TITLE
ReferenceError: LGTV is not defined

### ISSUE THREAD

**Issue by gammeflamme** [WesSouza/lgtv-ip-control#70]
lgtv-ip-controlled is installed globally but when trying to execute this simple code it errors out.

````js
const _ = require('lgtv-ip-control')

const tv = new LGTV('192.168.0.13', 'xx:xx:xx:xx:xx:xx', 'xxxxxxx');
````
error
````
C:\Program Files\nodejs\node.exe .\index.js
Uncaught ReferenceError: LGTV is not defined
Process exited with code 1

````

Attached is the entire project.

[monitor.zip](https://github.com/WesSouza/lgtv-ip-control/files/6913115/monitor.zip)

**Comment by WesSouza** [comment]
The package doesn't do anything if installed globally, it needs to be installed in the project's dependencies, and imported correctly:

```js
const LGTV = require('lgtv-ip-control')

const tv = new LGTV('192.168.0.13', 'xx:xx:xx:xx:xx:xx', 'xxxxxxx');
```
