### ISSUE TITLE
Readme Suggestion

### ISSUE THREAD

**Issue by kd8ssq** [WesSouza/lgtv-ip-control#79]
First off, let me say thank you for making this plugin.  You saved me a lot of time because I was gonna have to dig into the docs to figure out how to control our new lg displays.

In trying to set up the initial connection to the tv, I was not having any success following your steps in the readme.  After searching the internet for a while, I happened to look at previously submitted issues where someone asked for the document you referenced in the readme.  That's when I was finally able to make some progress.  

Your step #2 states "Using the remote arrows, navigate to "Connection". For some TVs, this may say "Network" instead." which to me meant that I had to go into the Connection/Network settings area.  The reference document said to "Keep the Network icon focused" (don't enter into the network area).  That was the key for me to be able to proceed.  Not sure if it's the same for all models, but if it is, I would suggest updating the Readme to indicate "highlighting, but not entering the network menu".

Thanks again

**Comment by WesSouza** [comment]
Good catch, tweaked it to mention "navigate the focus" and "do not enter it".
