### ISSUE TITLE
Package has type "module", but `main` refers to a CommonJS file

### ISSUE THREAD

**Issue by jadoc** [WesSouza/lgtv-ip-control#84]
If package.json has the property `type` set to "module", then Node interprets files with the ".js" extension as ESM. Currently, the `main` property refers to "dist/index.js", which contains CommonJS, but is erroneously interpreted as ESM due to `type` being set to "module". If the goal is to create a hybrid package, then I believe conditional exports should be used and the `type` property shouldn't be set at all. This conditional export worked for me:
```
  "exports": {
    "import": "./dist/index.mjs",
    "require": "./dist/index.js"
  },
```

This appears to have been broken at or near 633e2f68aa4c442659fbf072ce8eb0ad4fe0e4da.

**Comment by 404invalid-user** [comment]
i had this issue needed to download an older version for it to work with my existing code

**Comment by WesSouza** [comment]
My bad, I didn't read into proper ESM support when implementing.

I've updated the package to generate ESM as `.js`, and CommonJS as `.cjs` files, and added `"exports"` to the `package.json`.

Can you confirm 2.0.1 resolves this?

**Comment by jadoc** [comment]
Yes. The new config works well.
