### ISSUE TITLE
screenOff not working on LG C2

### ISSUE THREAD

**Issue by MatthiasGrandl** [WesSouza/lgtv-ip-control#88]
First of all, thanks for writing this library, it's very helpful!

I think LG probably must have changed the API a bit, but the energy saving option screenOff is not working for me. On my LG C2 this option is not at all in the same dropdown as the other energy saving options, but rather it's a separate button just outside of the energy saving menu.

My question is, how did you figure out all those commands? If I could figure out the command, I could open a PR, if you want.

Matthias

**Comment by WesSouza** [comment]
This is tricky.

IP controls are documented in some PDFs scattered through the web, which are not officially available through LG's website.

One that I found compatible with my TV series is in the [docs folder](https://github.com/WesSouza/lgtv-ip-control/blob/main/docs/LG_IP.pdf), and it lists most of the commands arguments used in this library. Others might have been added by contributors with different TV models.

Did you try `lgtv.setEnergySaving(EnergySavingLevels.screenOff)`? I wonder if it would just work even if it's not on the same menu.

**Comment by jadoc** [comment]
I've tested turning the screen off using the screen mute API I added in #90 on my C2.

**Comment by MatthiasGrandl** [comment]
tested your branch @jadoc and it works for me! thanks!

**Comment by Jibun-no-Kage** [comment]
I had to resort to send keys to turn feature on/off on my new LG TV 50RU90 series.

**Comment by Jibun-no-Kage** [comment]
Actually, I updated from the last commit, and got it working with my new LG as well.  Although the send keys method worked... it was really a kludge.  Thank you for actively supporting this solution!  I still plan to wrap this module into a Node Red palette, once I completely understand its implementation.
