### ISSUE TITLE
some functions do not working

### ISSUE THREAD

**Issue by demosspro** [WesSouza/lgtv-ip-control#92]
Hello, when i try run test script - it is give me an error, that you can see on screen. Were i am mistake?
![2023-03-17_16-40-36](https://user-images.githubusercontent.com/47609764/225921696-af26413f-a101-4175-9f94-7e4bd1043d72.png)

**Comment by jadoc** [comment]
There is nothing wrong with the library. You are attempting to use undefined symbols. You need to import the symbol `Inputs` before you can use it.

**Comment by demosspro** [comment]
oh, yeah, thank you! @jadoc it's work. i am some newbie in JS. 
i think there is need some examples to use. 
ie... Some loop functions
