### ISSUE TITLE
Additional input for freesat

### ISSUE THREAD

**Issue by o-Matt-o** [WesSouza/lgtv-ip-control#93]
Thanks for your work on this, I'm using it daily.

My tv is the LG OLED CX type (a UK model with a freesat tuner). I'd like to directly select this input I.e.

setInput('satdtv')

I tried setInput('dtv') but this selects the "Programme Mode" as "Antenna". 

Similarly, setInput('cadtv') select the "Programme Mode" as "Cable".

There seems to be no way to select "Programme Mode" as "Satellite".

I've tried adding the following items in constants/TV.d.ts... sdtv, sadtv, satdtv ... no joy.

**Comment by WesSouza** [comment]
Hard to say for sure, I can only offer some other thoughts of options, like:

```
sattv
sat
satv
```

**Comment by o-Matt-o** [comment]
Thanks for the quick response. I've tried those and unless there is another step I'm missing they don't seem to work either.

My workaround at the moment is to use sendKey('programGuide'). This is ok, so maybe I don't need a direct input select.

Just wondered if you had some other information source for these commands, I guess not.
Thanks again

**Comment by WesSouza** [comment]
It doesn't seem this use case is documented on openly available PDFs, the best I could find is [this one](http://www.proaudioinc.com/Dealer_Area/RS232C_EN_160526.pdf) which mentions satellite, but the section on Network IP Control is US only and doesn't mention satellite at all.
