### ISSUE TITLE
Example never exits?  Sorry not that familiar with JS?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [WesSouza/lgtv-ip-control#94]
Example never exits?  Sorry not that familiar with JS?  The following example works great, once I allow for 'require' versus using a module definition, but why it never exits?

`//import { LGTV } from 'lgtv-ip-control';

const delay = ms => new Promise(res => setTimeout(res, ms));
const { LGTV } = require('lgtv-ip-control');

const tv = new LGTV('192.168.1.87', '7C:64:6C:93:6F:06', 'ZH6WXH9P');

tv.connect()
  .then(async () => {

    const theVolume = await tv.getCurrentVolume()
    console.log('Volume '+theVolume)

    //console.log('Mute');
    //await tv.setVolumeMute(true);

    //delay(5000);

    //console.log('Unmute');
    //await tv.setVolumeMute(false);

  })
  .catch(console.error);
`

Something unique about JS that it can't exit the script when complete?

**Comment by Jibun-no-Kage** [comment]
Just dropped in the call function 'process.exit' so exit results.  I did notice one other issue, the powerOn function does not seem to work on my new 2023 50in LGTV.  But not surprised, because Wake on LAN is required to get the TV out of standby.

**Comment by jadoc** [comment]
If you don't want to work with JS, I've created some command line tools in a fork: https://github.com/jadoc/lgtv-ip-control/releases/tag/v3.1.0

**Comment by WesSouza** [comment]
@jadoc nice, we should work to merge those into one repo, with two separate packages for the lib and the cli.

**Comment by Jibun-no-Kage** [comment]
The thought was to do something more native to Windows OS.  JS is fine, but it does introduce an additional level of complexity... Not every Windows user is familiar with JS, nor do they realize it is embedded support in almost every browser.  Whereas in Linux, it is almost second nature to use node js when needed.  But the parallel to PowerShell in Windows (IMHO) is more applicable to Python in Linux.

An additional use case, would be to integrate to NodeRed, as a canned palette for NodeRed, versus raw JS in a NodeRed function node, for example.
